export const categories = [
    // Genre List
    {
      title: "Pop",
      type: "Genre",
      img: "url('../../../images/pop.png')",
      songs: [
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Advertising",
          src: "/musics/pop/advertising.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Tropical House",
          src: "/musics/pop/background-music.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Cheerful",
          src: "/musics/pop/cheerful.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Dance Tropical",
          src: "/musics/pop/dance-tropical.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Cheerful",
          src: "/musics/pop/cheerful.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Dance",
          src: "/musics/pop/dance.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Festival",
          src: "/musics/pop/festival.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Funny",
          src: "/musics/pop/funny.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "I see fire",
          src: "/musics/pop/i-see-fire.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Intro Future",
          src: "/musics/pop/intro-future.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Laten",
          src: "/musics/pop/laten-music.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Cooking",
          src: "/musics/pop/logo-cooking.mp3",
        },
  
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Playful",
          src: "/musics/pop/playful-musical.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Please Stay",
          src: "/musics/pop/please-stay.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Cooking",
          src: "/musics/pop/logo-cooking.mp3",
        },
  
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Pop Violin",
          src: "/musics/pop/pop-violin.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Rapport",
          src: "/musics/pop/rapport.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Solstice",
          src: "/musics/pop/solstice.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Street Dance",
          src: "/musics/pop/street-dance.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "The Future",
          src: "/musics/pop/the-future.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Uplifting",
          src: "/musics/pop/uplifting.mp3",
        },
      ],
    },
    {
      title: "Trap",
      type: "Genre",
      img: "url('../../../images/trap.jpg')",
      songs: [
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Golden",
          src: "/musics/trap/golden.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Happy Flute",
          src: "/musics/trap/happy-flute.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Hora",
          src: "/musics/trap/hora.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Knowledge",
          src: "/musics/trap/knowledge.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Modern",
          src: "/musics/trap/modern.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Murmur",
          src: "/musics/trap/murmur.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Pop",
          src: "/musics/trap/pop.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Royalty",
          src: "/musics/trap/royalty.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "Shine On",
          src: "/musics/trap/shine-on.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg",
          songName: "Tension",
          src: "/musics/trap/tension.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg",
          songName: "That Future",
          src: "/musics/trap/that-future.mp3",
        },
      ],
    },
    {
      title: "House",
      type: "Genre",
      img: "url('../../../images/house.jpg')",
      songs: [
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "24-sec",
          src: "/musics/house/24-sec.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Ambience",
          src: "/musics/house/ambience.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Ashes",
          src: "/musics/house/ashes.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Background",
          src: "/musics/house/background.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Feels Like Party",
          src: "/musics/house/feels-like-party.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Fiesta",
          src: "/musics/house/fiesta.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Intense",
          src: "/musics/house/intense.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Melody",
          src: "/musics/house/melody.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Nightmare",
          src: "/musics/house/nightmare.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Powerful",
          src: "/musics/house/powerful.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Rapport",
          src: "/musics/house/rapport.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Relaxed",
          src: "/musics/house/relaxed.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Rhythms",
          src: "/musics/house/rhythms.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Serenity",
          src: "/musics/house/serenity.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Summer",
          src: "/musics/house/summer.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Uplifting",
          src: "/musics/house/uplifting.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "War",
          src: "/musics/house/war.mp3",
        },
      ],
    },
    {
      title: "Beats",
      type: "Genre",
      img: "url('../../../images/beats.jpg')",
      songs: [
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Electro Sport",
          src: "/musics/beats/electro-sport.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Energy Sports",
          src: "/musics/beats/energy-sports.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Fashion Rock",
          src: "/musics/beats/fashion-rock.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Fashion Sport",
          src: "/musics/beats/fashion-sport.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Groovy Energy",
          src: "/musics/beats/groovy-energy.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Modern Fashion",
          src: "/musics/beats/modern-fashion.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Rock Beat",
          src: "/musics/beats/rock-beat.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Rock Beats",
          src: "/musics/beats/rock-beats.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Sexy Fashion",
          src: "/musics/beats/sexy-fashion.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Spin",
          src: "/musics/beats/spin.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Sport Rock",
          src: "/musics/beats/sport-rock.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Stylish Beat",
          src: "/musics/beats/stylish-beat.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Stylish Rock",
          src: "/musics/beats/stylish-rock.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img6.jpg", // Replace with actual image path
          songName: "Uplifting Day",
          src: "/musics/beats/uplifting-day.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img2.jpg", // Replace with actual image path
          songName: "Work It",
          src: "/musics/beats/work-it.mp3",
        },
      ],
    },
    {
      title: "Hip Hop",
      type: "Genre",
      img: "url('../../../images/hiphop.jpg')",
      songs: [
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Birds",
          src: "/musics/hip hop/birds.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Carol of the Bells",
          src: "/musics/hip hop/carol-of-the-bells.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Deck the Halls",
          src: "/musics/hip hop/deck-the-halls.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Double Apple",
          src: "/musics/hip hop/double-apple.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Jingle Bells",
          src: "/musics/hip hop/jingle-bells.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Modern",
          src: "/musics/hip hop/modern.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Move Forward",
          src: "/musics/hip hop/move-forward.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Mysterious",
          src: "/musics/hip hop/mysterious.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Newt",
          src: "/musics/hip hop/newt.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Slow Hiphop",
          src: "/musics/hip hop/slow-hiphop.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Small Town",
          src: "/musics/hip hop/small-town.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Smooth Soul",
          src: "/musics/hip hop/smooth-soul.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Stranger",
          src: "/musics/hip hop/stranger.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Street",
          src: "/musics/hip hop/street.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "That Rain",
          src: "/musics/hip hop/that-rain.mp3",
        },
        {
          singer: "Rema",
          time: "4:50",
          img: "../../../images/img8.jpg", // Replace with actual image path
          songName: "Urban",
          src: "/musics/hip hop/urban.mp3",
        },
        {
          singer: "Luke",
          time: "4:50",
          img: "../../../images/img4.jpg", // Replace with actual image path
          songName: "Vlog",
          src: "/musics/hip hop/vlog.mp3",
        },
      ],
    },
    {
      title: "Rock",
      type: "Genre",
      img: "url('../../../images/rock.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "Aggressive",
          src: "/musics/rock/aggressive.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Barbie",
          src: "/musics/rock/barbie.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img3.jpg",
          songName: "Barbiere",
          src: "/musics/rock/barbiere.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img4.jpg",
          songName: "Culmination",
          src: "/musics/rock/culmination.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img5.jpg",
          songName: "Energetic",
          src: "/musics/rock/energetic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img6.jpg",
          songName: "Groovy Rock",
          src: "/musics/rock/groovy-rock.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img7.jpg",
          songName: "Groovy",
          src: "/musics/rock/groovy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img8.jpg",
          songName: "Heavy Sports",
          src: "/musics/rock/heavy-sports.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img9.jpg",
          songName: "Metal",
          src: "/musics/rock/metal.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img1.jpg",
          songName: "Opening",
          src: "/musics/rock/opening.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img2.jpg",
          songName: "Sexy Fashion",
          src: "/musics/rock/sexy-fashion.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Sport",
          src: "/musics/rock/sport.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Stomping",
          src: "/musics/rock/stomping.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:05",
          img: "../../../images/img5.jpg",
          songName: "Stylish",
          src: "/musics/rock/stylish.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Welcome",
          src: "/musics/rock/welcome.mp3",
        },
      ],
    },
    {
      title: "Electro & Dance",
      type: "Genre",
      img: "url('../../../images/electro-dance.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:30",
          img: "../../../images/img1.jpg",
          songName: "Boom",
          src: "/musics/electro and dance/boom.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img3.jpg",
          songName: "Dance Tropical",
          src: "/musics/electro and dance/dance-tropical.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Fashion Electronic",
          src: "/musics/electro and dance/fashion-electronic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img7.jpg",
          songName: "Fresh",
          src: "/musics/electro and dance/fresh.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img9.jpg",
          songName: "Good Feelings",
          src: "/musics/electro and dance/good-feelings.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img5.jpg",
          songName: "Lazer Note",
          src: "/musics/electro and dance/lazer-note.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img6.jpg",
          songName: "Like a Boss",
          src: "/musics/electro and dance/like-a-boss.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:05",
          img: "../../../images/img7.jpg",
          songName: "Passage",
          src: "/musics/electro and dance/passage.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Playful",
          src: "/musics/electro and dance/playful.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Powerful",
          src: "/musics/electro and dance/powerful.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Riding the Wave",
          src: "/musics/electro and dance/riding-the-wave.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Ringing Success",
          src: "/musics/electro and dance/ringing-success.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img6.jpg",
          songName: "Rising from Ashes",
          src: "/musics/electro and dance/rising-from-ashes.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Silver Lake",
          src: "/musics/electro and dance/silver-lake.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:35",
          img: "../../../images/img1.jpg",
          songName: "Stomps Seeker",
          src: "/musics/electro and dance/stomps-seeker.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img3.jpg",
          songName: "Summer Dance",
          src: "/musics/electro and dance/summer-dance.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img4.jpg",
          songName: "The Fighter",
          src: "/musics/electro and dance/the-fighter.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "The Future",
          src: "/musics/electro and dance/the-future.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img7.jpg",
          songName: "Tropical House",
          src: "/musics/electro and dance/tropical-house.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img6.jpg",
          songName: "War Teaser",
          src: "/musics/electro and dance/war-teaser.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img8.jpg",
          songName: "Windmill",
          src: "/musics/electro and dance/windmill.mp3",
        },
      ],
    },
    {
      title: "Funk",
      type: "Genre",
      img: "url('../../../images/funk.jpeg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img7.jpg",
          songName: "At the Party",
          src: "/musics/funk/at-the-party.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Big City",
          src: "/musics/funk/big-city.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "City Pop",
          src: "/musics/funk/city-pop.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Energetic Funky",
          src: "/musics/funk/energetic-funky.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img4.jpg",
          songName: "Energetic",
          src: "/musics/funk/energetic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img6.jpg",
          songName: "Funk Guitar",
          src: "/musics/funk/funk-guitar.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img8.jpg",
          songName: "Funk",
          src: "/musics/funk/funk.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Funky Burger",
          src: "/musics/funk/funky-burger.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img5.jpg",
          songName: "Funky Pop",
          src: "/musics/funk/funky-pop.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "Funky",
          src: "/musics/funk/funky.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Getaway",
          src: "/musics/funk/getaway.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img7.jpg",
          songName: "Happy Birthday",
          src: "/musics/funk/happy-birthday.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img8.jpg",
          songName: "Slue",
          src: "/musics/funk/slue.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img9.jpg",
          songName: "Smoking Barrel",
          src: "/musics/funk/smoking-barrel.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img1.jpg",
          songName: "Spy",
          src: "/musics/funk/spy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Street Dancer",
          src: "/musics/funk/street-dancer.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Thought",
          src: "/musics/funk/thought.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Upbeat Funk",
          src: "/musics/funk/upbeat-funk.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Vasabi",
          src: "/musics/funk/vasabi.mp3",
        },
      ],
    },
  
    // Mood List
    {
      title: "Happy",
      type: "Mood",
      img: "url('../../../images/happy.jpg')",
      songs: [
        // Happy folder
        {
          singer: "Unknown Artist",
          time: "3:20",
          img: "../../../images/img1.jpg",
          songName: "Baby",
          src: "/musics/happy/baby.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Catch It",
          src: "/musics/happy/catch-it.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Dance Mood",
          src: "/musics/happy/dance-mood.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img4.jpg",
          songName: "Happy Day",
          src: "/musics/happy/happy-day.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Happy Santa",
          src: "/musics/happy/happy-santa.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img6.jpg",
          songName: "Happy",
          src: "/musics/happy/happy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img7.jpg",
          songName: "In Color",
          src: "/musics/happy/in-color.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Jazz",
          src: "/musics/happy/jazz.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Jingle Bells",
          src: "/musics/happy/jingle-bells.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img1.jpg",
          songName: "Quirky",
          src: "/musics/happy/quirky.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Running",
          src: "/musics/happy/running.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Santa",
          src: "/musics/happy/santa.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img4.jpg",
          songName: "Santa Medium",
          src: "/musics/happy/santa_medium.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img5.jpg",
          songName: "Summer Vibes",
          src: "/musics/happy/summer-vibes.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:35",
          img: "../../../images/img6.jpg",
          songName: "Trap Sax",
          src: "/musics/happy/trap-sax.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img7.jpg",
          songName: "Tropical Summer",
          src: "/musics/happy/tropical-summer.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img8.jpg",
          songName: "Upbeat Ukulele",
          src: "/musics/happy/upbeat-ukulele.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img9.jpg",
          songName: "Uplifting",
          src: "/musics/happy/uplifting.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "Whistle Vibes",
          src: "/musics/happy/whistle-vibes.mp3",
        },
      ],
    },
    {
      title: "Angry",
      type: "Mood",
      img: "url('../../../images/angry.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img1.jpg",
          songName: "Action",
          src: "/musics/angry/action.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Cyberpunk",
          src: "/musics/angry/cyberpunk.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Dark Mystery",
          src: "/musics/angry/dark-mystery.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Dark Side",
          src: "/musics/angry/dark-side.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Fashion",
          src: "/musics/angry/fashion.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img6.jpg",
          songName: "Friendly Ghost",
          src: "/musics/angry/friendly-ghost.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img7.jpg",
          songName: "Hard Big",
          src: "/musics/angry/hard-big.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Horror",
          src: "/musics/angry/horror.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Insurrection",
          src: "/musics/angry/insurrection.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img1.jpg",
          songName: "Intense",
          src: "/musics/angry/intense.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Knockout Blow",
          src: "/musics/angry/knockout-blow.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Metal Dubstep",
          src: "/musics/angry/metal-dubstep.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img4.jpg",
          songName: "Nuclear Bomb",
          src: "/musics/angry/nuclear-bomb.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img5.jpg",
          songName: "Rock Riff",
          src: "/musics/angry/rock-riff.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img6.jpg",
          songName: "Scary Horror",
          src: "/musics/angry/scary-horror.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Shooter",
          src: "/musics/angry/shooter.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img8.jpg",
          songName: "Start the Engine",
          src: "/musics/angry/start-the-engine.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Strong",
          src: "/musics/angry/strong.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:05",
          img: "../../../images/img1.jpg",
          songName: "Thrash",
          src: "/musics/angry/thrash.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img2.jpg",
          songName: "Trap",
          src: "/musics/angry/trap.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img3.jpg",
          songName: "Urban Gangster",
          src: "/musics/angry/urban-gangster.mp3",
        },
      ],
    },
    {
      title: "Romantic",
      type: "Mood",
      img: "url('../../../images/romantic.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:25",
          img: "../../../images/img1.jpg",
          songName: "A Small Miracle",
          src: "/musics/romantic/a-small-miracle.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img2.jpg",
          songName: "Ambient Guitar",
          src: "/musics/romantic/ambient-guitar.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img3.jpg",
          songName: "Ambient Piano",
          src: "/musics/romantic/ambient-piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img4.jpg",
          songName: "Bossa Nova",
          src: "/musics/romantic/bossa-nova.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img5.jpg",
          songName: "Cinematic",
          src: "/musics/romantic/cinematic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img6.jpg",
          songName: "Dramatic",
          src: "/musics/romantic/dramatic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img7.jpg",
          songName: "Fairy Tale",
          src: "/musics/romantic/fairy-tale.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img8.jpg",
          songName: "Flamenco Rose",
          src: "/musics/romantic/flamenco-rose.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img9.jpg",
          songName: "Forget",
          src: "/musics/romantic/forget.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "French",
          src: "/musics/romantic/french.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Gypsy",
          src: "/musics/romantic/gypsy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img3.jpg",
          songName: "Hope Piano",
          src: "/musics/romantic/hope-piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img4.jpg",
          songName: "Inspiring",
          src: "/musics/romantic/inspiring.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:05",
          img: "../../../images/img5.jpg",
          songName: "Jazz",
          src: "/musics/romantic/jazz.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img6.jpg",
          songName: "Love Story",
          src: "/musics/romantic/love-story.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img7.jpg",
          songName: "Love",
          src: "/musics/romantic/love.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img8.jpg",
          songName: "Lovely Time",
          src: "/musics/romantic/lovely-time.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Melody",
          src: "/musics/romantic/melody.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img1.jpg",
          songName: "My Life",
          src: "/musics/romantic/my-life.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img2.jpg",
          songName: "Night Jazz",
          src: "/musics/romantic/night-jazz.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img3.jpg",
          songName: "Ripple Chinese",
          src: "/musics/romantic/ripple-chinese.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img4.jpg",
          songName: "Romantic",
          src: "/musics/romantic/romantic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Sensual",
          src: "/musics/romantic/sensual.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img6.jpg",
          songName: "Silent Night",
          src: "/musics/romantic/silent-night.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img7.jpg",
          songName: "Sunset by the Sea",
          src: "/musics/romantic/sunset-by-the-sea.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "The Flashback",
          src: "/musics/romantic/the-flashback.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img9.jpg",
          songName: "The Virgin",
          src: "/musics/romantic/the-virgin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img1.jpg",
          songName: "Uplifting",
          src: "/musics/romantic/uplifting.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img2.jpg",
          songName: "Voice of Nature",
          src: "/musics/romantic/voice-of-nature.mp3",
        },
      ],
    },
    {
      title: "Mysterious",
      type: "Mood",
      img: "url('../../../images/mysterious.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img3.jpg",
          songName: "80s Mystical",
          src: "/musics/mysterious/80s-mystical.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img4.jpg",
          songName: "A Creepy Music",
          src: "/musics/mysterious/a-creepy-music.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img5.jpg",
          songName: "An Alien Presence",
          src: "/musics/mysterious/an-alien-presence.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img6.jpg",
          songName: "Dark Action",
          src: "/musics/mysterious/dark-action.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img7.jpg",
          songName: "Dark Mystery",
          src: "/musics/mysterious/dark-mystery.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img8.jpg",
          songName: "Depressive Anxious",
          src: "/musics/mysterious/depressive-anxious.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img9.jpg",
          songName: "Dramatic",
          src: "/musics/mysterious/dramatic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img1.jpg",
          songName: "Fluidity",
          src: "/musics/mysterious/fluidity.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img2.jpg",
          songName: "Footsteps in the Dark",
          src: "/musics/mysterious/footsteps-in-the-dark.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img3.jpg",
          songName: "Forest Creepy",
          src: "/musics/mysterious/forest-creepy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img4.jpg",
          songName: "Horror Intro",
          src: "/musics/mysterious/horror-intro.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img5.jpg",
          songName: "Horror",
          src: "/musics/mysterious/horror.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Last Days",
          src: "/musics/mysterious/last-days.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img7.jpg",
          songName: "Light",
          src: "/musics/mysterious/light.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Magic in the Air",
          src: "/musics/mysterious/magic-in-the-air.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img9.jpg",
          songName: "Mysterious Celesta",
          src: "/musics/mysterious/mysterious-celesta.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img1.jpg",
          songName: "Mysterious Cinematic",
          src: "/musics/mysterious/mysterious-cinematic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img2.jpg",
          songName: "Mysterious Music",
          src: "/musics/mysterious/mysterious-music.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img3.jpg",
          songName: "Mysterious",
          src: "/musics/mysterious/mysterious.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img4.jpg",
          songName: "Mystical Music",
          src: "/musics/mysterious/mystical-music.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img5.jpg",
          songName: "Shadow Behind",
          src: "/musics/mysterious/shadow-behind.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img6.jpg",
          songName: "Superhero",
          src: "/musics/mysterious/superhero.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Tension",
          src: "/musics/mysterious/tension.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img8.jpg",
          songName: "That Halloween",
          src: "/musics/mysterious/that-halloween.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Walth",
          src: "/musics/mysterious/walth.mp3",
        },
      ],
    },
    {
      title: "Fear",
      type: "Mood",
      img: "url('../../../images/fear.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Attacking",
          src: "/musics/fear/Attacking.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Cold Fear",
          src: "/musics/fear/Cold Fear.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Crysis",
          src: "/musics/fear/Crysis.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Damage",
          src: "/musics/fear/Damage.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Distraction",
          src: "/musics/fear/Distraction.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Fear Evolved",
          src: "/musics/fear/Fear Evolved.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Fear Rules",
          src: "/musics/fear/Fear Rules.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img8.jpg",
          songName: "Head Over",
          src: "/musics/fear/Head Over.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Horror",
          src: "/musics/fear/Horror.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img1.jpg",
          songName: "Psycho",
          src: "/musics/fear/Psycho.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img2.jpg",
          songName: "Shocked",
          src: "/musics/fear/Shocked.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img3.jpg",
          songName: "Spooky",
          src: "/musics/fear/Spooky.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img4.jpg",
          songName: "Tears",
          src: "/musics/fear/Tears.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:25",
          img: "../../../images/img5.jpg",
          songName: "Underground",
          src: "/musics/fear/Underground.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img6.jpg",
          songName: "Winds",
          src: "/musics/fear/Winds.mp3",
        },
      ],
    },
    {
      title: "Sad",
      type: "Mood",
      img: "url('../../../images/sad.jpg')",
      songs: [
        // SAD folder
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img1.jpg",
          songName: "Alone",
          src: "/musics/sad/Alone.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img2.jpg",
          songName: "Death",
          src: "/musics/sad/Death.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:10",
          img: "../../../images/img3.jpg",
          songName: "Depressed",
          src: "/musics/sad/Depressed.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img4.jpg",
          songName: "Distance",
          src: "/musics/sad/Distance.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img5.jpg",
          songName: "Fluke",
          src: "/musics/sad/Fluke.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img6.jpg",
          songName: "Grief",
          src: "/musics/sad/Grief.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img7.jpg",
          songName: "Heart Broken",
          src: "/musics/sad/Heart Broken.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Last Dawn",
          src: "/musics/sad/Last Dawn.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img9.jpg",
          songName: "Lonely",
          src: "/musics/sad/Lonely.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Mourn",
          src: "/musics/sad/Mourn.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Regret",
          src: "/musics/sad/Regret.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Sadness",
          src: "/musics/sad/Sadness.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Sorrow",
          src: "/musics/sad/Sorrow.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Turk",
          src: "/musics/sad/Turk.mp3",
        },
      ],
    },
    {
      title: "Scary",
      type: "Mood",
      img: "url('../../../images/scary.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img1.jpg",
          songName: "Appalling",
          src: "/musics/scary/Appalling.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Creepy",
          src: "/musics/scary/Creepy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img3.jpg",
          songName: "Darkness",
          src: "/musics/scary/Darkness.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Fearsome",
          src: "/musics/scary/Fearsome.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Frightening",
          src: "/musics/scary/Frightening.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img6.jpg",
          songName: "Halloween",
          src: "/musics/scary/Halloween.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img7.jpg",
          songName: "Horrifying",
          src: "/musics/scary/Horrifying.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Killer",
          src: "/musics/scary/Killer.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Scared",
          src: "/musics/scary/Scared.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img1.jpg",
          songName: "Scary",
          src: "/musics/scary/Scary.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img2.jpg",
          songName: "Sinister",
          src: "/musics/scary/Sinister.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img3.jpg",
          songName: "Terrifying",
          src: "/musics/scary/Terrifying.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img4.jpg",
          songName: "Timid",
          src: "/musics/scary/Timid.mp3",
        },
      ],
    },
    {
      title: "Suspense",
      type: "Mood",
      img: "url('../../../images/suspense.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "Anticipated",
          src: "/musics/suspense/Anticipated.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Anxious",
          src: "/musics/suspense/Anxious.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img3.jpg",
          songName: "Doubting",
          src: "/musics/suspense/Doubting.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img4.jpg",
          songName: "Exciting",
          src: "/musics/suspense/Exciting.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img5.jpg",
          songName: "Feelings",
          src: "/musics/suspense/Feelings.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img6.jpg",
          songName: "Hurt",
          src: "/musics/suspense/Hurt.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img7.jpg",
          songName: "Shocking",
          src: "/musics/suspense/Shocking.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Spirit",
          src: "/musics/suspense/Spirit.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img9.jpg",
          songName: "Suss Beats",
          src: "/musics/suspense/Suss Beats.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img1.jpg",
          songName: "Thirsty",
          src: "/musics/suspense/Thirsty.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img2.jpg",
          songName: "Uneasy",
          src: "/musics/suspense/Uneasy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img3.jpg",
          songName: "Worried",
          src: "/musics/suspense/Worried.mp3",
        },
      ],
    },
  
    // Instrument list
    {
      title: "Piano",
      type: "Instrument",
      img: "url('../../../images/piano.jpg')",
      songs: [
        // piano folder
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Airplanes",
          src: "/musics/piano/Airplanes.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Beast",
          src: "/musics/piano/Beast.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Cool Piano",
          src: "/musics/piano/Cool_Piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Crazy",
          src: "/musics/piano/Crazy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Dawn",
          src: "/musics/piano/Dawn.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Haze",
          src: "/musics/piano/Haze.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Lightning",
          src: "/musics/piano/Lightning.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Madly",
          src: "/musics/piano/Madly.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Persian",
          src: "/musics/piano/Persian.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Romantic Piano",
          src: "/musics/piano/Romantic Piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Sad Piano",
          src: "/musics/piano/Sad Piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Sunrise",
          src: "/musics/piano/Sunrise.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Sweet Piano",
          src: "/musics/piano/Sweet Piano.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Terrific",
          src: "/musics/piano/Terrific.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img6.jpg",
          songName: "Thunder",
          src: "/musics/piano/Thunder.mp3",
        },
      ],
    },
    {
      title: "Violin",
      type: "Instrument",
      img: "url('../../../images/violins.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img7.jpg",
          songName: "Balad Violin",
          src: "/musics/violin/Balad Violin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Broken",
          src: "/musics/violin/Broken.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img9.jpg",
          songName: "Devil",
          src: "/musics/violin/Devil.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img1.jpg",
          songName: "Hallelujah",
          src: "/musics/violin/Hallelujah.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img2.jpg",
          songName: "Historical Violin",
          src: "/musics/violin/Historical Violin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img3.jpg",
          songName: "Jules Massenet",
          src: "/musics/violin/Jules Massenet.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img4.jpg",
          songName: "Onepiece Violin",
          src: "/musics/violin/Onepiece Violin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img5.jpg",
          songName: "Pietro Violin",
          src: "/musics/violin/Pietro Violin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img6.jpg",
          songName: "Romantic Violin",
          src: "/musics/violin/Romantic Violin.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img7.jpg",
          songName: "Stirling",
          src: "/musics/violin/Stirling.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img8.jpg",
          songName: "Summers",
          src: "/musics/violin/Summers.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Thrills",
          src: "/musics/violin/Thrills.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img1.jpg",
          songName: "Windy Violin",
          src: "/musics/violin/Windy Violin.mp3",
        },
      ],
    },
    {
      title: "Flute",
      type: "Instrument",
      img: "url('../../../images/Flute.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img1.jpg",
          songName: "Attractive",
          src: "/musics/flute/Attractive.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Bengali Flute",
          src: "/musics/flute/Bengali Flute.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Dragon Flute",
          src: "/musics/flute/Dragon Flute.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Dreams",
          src: "/musics/flute/Dreams.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Fairy Flute",
          src: "/musics/flute/Fairy_Flute.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Feelings",
          src: "/musics/flute/Feelings.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Imagination",
          src: "/musics/flute/Imagination.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Mead",
          src: "/musics/flute/Mead.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Musically",
          src: "/musics/flute/Musically.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Romantic",
          src: "/musics/flute/Romantic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Soul",
          src: "/musics/flute/Soul.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Sweet",
          src: "/musics/flute/Sweet.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Tragic",
          src: "/musics/flute/Tragic.mp3",
        },
      ],
    },
    {
      title: "Guitar",
      type: "Instrument",
      img: "url('../../../images/Guitar.jpg')",
  
      songs: [
        // guitar folder
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Attached",
          src: "/musics/guitar/Attached.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Attractive",
          src: "/musics/guitar/Attractive.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Blues Guitar",
          src: "/musics/guitar/Blues_Guitar.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Cemetery",
          src: "/musics/guitar/Cemetery.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Distortion",
          src: "/musics/guitar/Distortion.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Electrifying",
          src: "/musics/guitar/Electrifying.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Futuristic",
          src: "/musics/guitar/Futuristic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Guitartastic",
          src: "/musics/guitar/Guitartastic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Love",
          src: "/musics/guitar/Love.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Nexus",
          src: "/musics/guitar/Nexus.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Shreds",
          src: "/musics/guitar/Shreds.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Slow Guitar",
          src: "/musics/guitar/Slow Guitar.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Solo Guitar",
          src: "/musics/guitar/Solo Guitar.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Tears",
          src: "/musics/guitar/Tears.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img6.jpg",
          songName: "Vibes",
          src: "/musics/guitar/Vibes.mp3",
        },
      ],
    },
    {
      title: "Accordion",
      type: "Instrument",
      img: "url('../../../images/Accordion.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "3:40",
          img: "../../../images/img7.jpg",
          songName: "Athletic",
          src: "/musics/accordion/Athletic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img8.jpg",
          songName: "Blackeyes",
          src: "/musics/accordion/Blackeyes.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img9.jpg",
          songName: "Candles",
          src: "/musics/accordion/Candles.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img1.jpg",
          songName: "Classical",
          src: "/musics/accordion/Classical.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img2.jpg",
          songName: "Indian",
          src: "/musics/accordion/Indian.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img3.jpg",
          songName: "Light",
          src: "/musics/accordion/Light.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img4.jpg",
          songName: "Loving",
          src: "/musics/accordion/Loving.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img5.jpg",
          songName: "Rose",
          src: "/musics/accordion/Rose.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img6.jpg",
          songName: "Turkish",
          src: "/musics/accordion/Turkish.mp3",
        },
      ],
    },
    {
      title: "Drums",
      type: "Instrument",
      img: "url('../../../images/Drum.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img1.jpg",
          songName: "African",
          src: "/musics/drums/African.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Amaze",
          src: "/musics/drums/Amaze.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Arabic Drum",
          src: "/musics/drums/Arabic Drum.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Beat",
          src: "/musics/drums/Beat.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Cheering",
          src: "/musics/drums/Cheering.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Drum Interval",
          src: "/musics/drums/Drum_Interval.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Drum Line",
          src: "/musics/drums/Drum_Line.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Electric",
          src: "/musics/drums/Electric.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Finite",
          src: "/musics/drums/Finite.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Heat",
          src: "/musics/drums/Heat.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Heavy Drums",
          src: "/musics/drums/Heavy_Drums.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Mix Drums",
          src: "/musics/drums/Mix Drums.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Noise",
          src: "/musics/drums/Noise.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Solo Drum",
          src: "/musics/drums/Solo Drum.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img6.jpg",
          songName: "Vintage",
          src: "/musics/drums/Vintage.mp3",
        },
      ],
    },
    {
      title: "Harmonica",
      type: "Instrument",
      img: "url('../../../images/Harmonica.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img1.jpg",
          songName: "Bright",
          src: "/musics/harmonica/Bright.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Busy Cafes",
          src: "/musics/harmonica/Busy Cafes.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Cold Blows",
          src: "/musics/harmonica/Cold Blows.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Counting Stars",
          src: "/musics/harmonica/Counting Stars.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Dancing Harmonica",
          src: "/musics/harmonica/Dancing Harmonica.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Fast",
          src: "/musics/harmonica/Fast.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Heaven",
          src: "/musics/harmonica/Heaven.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "Loop",
          src: "/musics/harmonica/Loop.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Moonlight",
          src: "/musics/harmonica/Moonlight.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "One Republic",
          src: "/musics/harmonica/One Republic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Playing At Work",
          src: "/musics/harmonica/Playing At Work.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Romans",
          src: "/musics/harmonica/Romans.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Romantic",
          src: "/musics/harmonica/Romantic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Soft",
          src: "/musics/harmonica/Soft.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img6.jpg",
          songName: "Soundful",
          src: "/musics/harmonica/Soundful.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Winds",
          src: "/musics/harmonica/Winds.mp3",
        },
      ],
    },
    {
      title: "Xylophone",
      type: "Instrument",
      img: "url('../../../images/Xylophone.jpg')",
      songs: [
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img1.jpg",
          songName: "Acoustic",
          src: "/musics/xylophone/Acoustic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img2.jpg",
          songName: "Classy",
          src: "/musics/xylophone/Classy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Clouds",
          src: "/musics/xylophone/Clouds.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:30",
          img: "../../../images/img4.jpg",
          songName: "Dance Floor",
          src: "/musics/xylophone/Dance Floor.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:50",
          img: "../../../images/img5.jpg",
          songName: "Dreamy",
          src: "/musics/xylophone/Dreamy.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:15",
          img: "../../../images/img6.jpg",
          songName: "Emptiness",
          src: "/musics/xylophone/Emptyness.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img7.jpg",
          songName: "Focus",
          src: "/musics/xylophone/Focus.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img8.jpg",
          songName: "High Heels",
          src: "/musics/xylophone/High Heels.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img9.jpg",
          songName: "Japanese Xylophone",
          src: "/musics/xylophone/Japanese xylophone.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img1.jpg",
          songName: "Magic",
          src: "/musics/xylophone/Magic.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:00",
          img: "../../../images/img2.jpg",
          songName: "Pillowtalk",
          src: "/musics/xylophone/Pillowtalk.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:55",
          img: "../../../images/img3.jpg",
          songName: "Ringtone",
          src: "/musics/xylophone/Ringtone.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "4:20",
          img: "../../../images/img4.jpg",
          songName: "Shocklee",
          src: "/musics/xylophone/Shocklee.mp3",
        },
        {
          singer: "Unknown Artist",
          time: "3:45",
          img: "../../../images/img5.jpg",
          songName: "Wooden Xylophone",
          src: "/musics/xylophone/Wooden xylophone.mp3",
        },
      ],
    },
  ];